apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: ClusterIP # Cambia a LoadBalancer o NodePort si necesitas acceso externo
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80 # Puerto del servicio
    targetPort: 80 # Puerto en el contenedor